// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SourceFullStoreDb;

namespace SourceFullStoreDb.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200817074806_Cities")]
    partial class Cities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("Domain.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kielce",
                            Size = 250000
                        },
                        new
                        {
                            Id = 2,
                            Name = "Łódź",
                            Size = 550000
                        },
                        new
                        {
                            Id = 3,
                            Name = "Lublin",
                            Size = 450000
                        });
                });

            modelBuilder.Entity("Domain.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Szymon",
                            Surname = "Nowutyuicki"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Szymoasdas",
                            Surname = "Nutyowicki"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Szydasdmon",
                            Surname = "Noutyuwicki"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Szeerewymon",
                            Surname = "Notyutwicki"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Szymbvcbon",
                            Surname = "Nowityutcki"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Szymbvcbon",
                            Surname = "Nowutyuicki"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Szymhgjghon",
                            Surname = "Notyutwicki"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Szymjghjgon",
                            Surname = "Nowiutyucki"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
