// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SourceFullStoreDb;

namespace SourceFullStoreDb.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("Domain.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kielce",
                            Size = 250000
                        },
                        new
                        {
                            Id = 2,
                            Name = "Łódź",
                            Size = 550000
                        },
                        new
                        {
                            Id = 4,
                            Name = "Lublin",
                            Size = 450000
                        },
                        new
                        {
                            Id = 5,
                            Name = "Końskie",
                            Size = 780000
                        },
                        new
                        {
                            Id = 6,
                            Name = "Warszawa",
                            Size = 21250000
                        });
                });

            modelBuilder.Entity("Domain.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Adam",
                            Surname = "Backers"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Davis",
                            Surname = "Clarck"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Frank",
                            Surname = "Evans"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Irwin",
                            Surname = "Jones"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Troth",
                            Surname = "Smith"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
